name: airmonlink_business_manager
description: Offline-first Windows POS, inventory, customer, supplier, expense and reporting software.
publish_to: none
version: 1.0.1+4

environment:
  sdk: '>=3.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: 0.20.2
  path: 1.9.1
  path_provider: 2.1.6
  pdf: 3.13.0
  printing: 5.15.0
  sqflite_common_ffi: 2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0

flutter:
  uses-material-design: true
